### PR TITLE
Callistonian edits 10/14/22

### LINKED ISSUE #6: Add event "onCharacterMarriesPrincess"
The **onCharacterMarries** function does not work when marrying princesses - it only works with regular wives from the family tree. There are two separate events for princesses in medieval2:
-for ordinary women
 `CharacterMarries`
-for princesses
`CharacterMarriesPrincess`
Скриншот 05-08-2022 224436

### PR DESCRIPTION
**Pull request by Callistonian**
- commented out recruit pool edits from July 26 commit which were crashing the game, left toolRoutine.h and the EduIndex fixes alone
- fixed and improved a lot of Lua documentation
- added the rest of the character attribute fields to the named character structure, changed type of all attribute members of the generalCharacterictics structure to int32_t
- added event functions to Lua: onShortcutTriggered(), onCharacterMarriesPrincess(), onBecomesFactionLeader(), onBecomesFactionHeir()
- added structures to Lua: portStruct, watchtowerStruct, factionStratMap, buildingsQueue, buildingInQueue
- fixed subElement index being incremented by +1 which makes iterating through sub elements from 0 to (subElementsnum-1) return the correct results in Lua, getSubElement() returns uiElementStruct in the documentation
- fixed bug so that setting resource strat models no longer sets their cost and hasMine fields to 0
- renamed "getResourceCode" to "getResourceID" for uniformity with rest of the ID fields in Lua, added hasMine getter for the resource structure, renamed "resStrat" to "tradeResource", added getters for hasMine and tga
	- WARNING: current usage incompatibility (getResourceCode)
- fixed soldierCountStratMapMax and soldierCountBattleMap being swapped and returning incorrect values

### CODE REVIEW

**Comment by Medik-GH** [comment]
Isn't the documentation for the Lua stuff generated from `luaP.cpp` or `luaP2.cpp` ? I don't see them there.

If you could also update the https://github.com/youneuoy/M2TWEOP-library/blob/master/docs/releaseInfo/releaseDescription.md with your changes that would be helpful (including removing anything you've commented out like youns stuff). Would like to do a release very soon.

Apart from that it looks good to me! Nice work!

**Comment by Callistonian** [comment]
I pushed luaP.cpp and luaP2.cpp to the luaPlugin. It seems my original commit worked and is still there under the same pull request (for some reason even after I deleted the branch). Obviously, only one of those commits is needed but I don't see how to cancel/delete the other. I'm sort of hoping that someone around here will be able to make sense of all this so that I can do a clean clone of the latest build (with things like the luaPlugin submodule issue and the documentation showing up in the Git Changes having been resolved).

I'll try to commit releaseDescription.md.

**Review by Callistonian — COMMENTED** [review]
No conflicts here.

**Comment by Medik-GH** [comment]
I've done the following

* Updated both the Library and LuaPlugin PR's so they are up to date with master
* Updated the release notes with Callis changes and added a breaking changes section
* Built EOP with both this version of Library and Callis other version of LuaPlugin (All good,  no errors)
* Installed it fresh and tested calling a lua function (all good)
* Checked the built documentation includes his latest changes (it does)

Everything seems good to me 👍

**Comment by yaneay** [comment]
all look ok

**Pull request merged**
